package fr.mines.android.exercises;

import java.util.Arrays;
import java.util.List;

public class MoviesDb {


    private MoviesDb() {

    }

    public static List<Movie> movies = Arrays.asList(
            new Movie(R.drawable.it_follows, "IT FOLLOWS", "Feb 4, 2015 Wide", "After a strange sexual encounter, a teenager finds herself haunted by nightmarish visions and the inescapable sense that something is after her. (C) Radius-TWC"),
            new Movie(R.drawable.the_misfits, "THE MISFITS", "Apr 7, 1961 Wide", "The final film of stars Clark Gable and Marilyn Monroe is an elegy for the death of the Old West from writer Arthur Miller and director John Huston. Gable stars as Gay Langland, an aging hand traveling the byways and working at rodeos with his two comrades, Guido (Eli Wallach) and young Perce Howland (Montgomery Clift). The three men come up with a plan to corral some misfit mustangs and sell them for dog food, but Gay's new girlfriend Roslyn Taber (Marilyn Monroe), a high-minded ex-stripper who has just divorced her husband Ray (Kevin McCarthy) in Reno, is appalled by the plan. Although both Guido and Perce are also in love with Roslyn, she stands by Gay, sure that in the end he will do the right thing, even as he and his pals begin their planned roundup."),
            new Movie(R.drawable.hard_to_be_a_god, "HARD TO BE A GOD", "Feb 11, 2015 Wide", "When legendary Russian auteur Aleksei German died in 2013, he left behind this extraordinary final film, a phantasmagoric adaptation of the revered sci-fi novel by the Strugatsky brothers (authors of the source novel for Tarkovsky's STALKER). HARD TO BE A GOD began percolating in German's consciousness in the mid-1960s, and would actively consume him for the last 15 years of his life. Happily, he brought the film close enough to completion for his wife and son to apply the finishing touches immediately after his passing. Taking place on the planet Arkanar, which is in the midst of its own Middle Ages, the film focuses on Don Rumata, one of a group of earth scientists who have been sent to Arkanar with the proviso that they must not interfere in the planet's political or historical development. Treated by the planet's natives as a kind of divinity, Don Rumata is both godlike and impotent in the face of its chaos and brutality. (C) Kino Lorber"),
            new Movie(R.drawable.amour_fou, "AMOUR FOU", "Feb 4, 2015 Wide", "Berlin, 1810: Heinrich von Kleist (1777 - 1811), a despondent young poet/dramatist, pines for a woman to join him in a pact to end his despair - and which, absurdly, he conceives as the ultimate expression of romantic love. To this end, he meets Henrietta Vogel, a high-society lady who is fascinated by his controversial novella, The Marquise of O. Inspired by the historical events that led to this famed double suicide, Austrian director Jessica Hausner vividly imagines early 19th century haute bourgeois Berlin: the hushed drawing rooms, deliberate rhythms of family life, the period décor and clothing - all suffused with a color scheme worthy of Vermeer. (C) Film "),
            new Movie(R.drawable.merveilles, "MERVEILLES", "Feb 15, 2015 Wide", "Rohrwacher's richly textured sophomore feature centers on a family of beekeepers living in stark isolation in central Italy. The dynamic of their overcrowded household is disrupted by the simultaneous arrival of a silently troubled teenaged boy taken in as a farmhand, and a production crew recruiting local farmers to participate in a cheesy televised celebration of ancient Etruscan culture presented by the mysterious Milly Catena (Monica Bellucci). Both intrusions are of particular interest to the eldest daughter, Gelsomina, who is struggling to find her footing in the world, and Rohrwacher manages to convey her adolescent sense of wonder and confusion with characteristically graceful naturalism."),
            new Movie(R.drawable.phoenix, "PHOENIX", "Jan 28, 2015 Wide", null),
            new Movie(R.drawable.mr_turner, "MR. TURNER", "Dec 3, 2014 Wide", "This film explores the last quarter century of the great if eccentric British painter J.M.W. Turner (1775-1851). Profoundly affected by the death of his father, loved by a housekeeper he takes for granted and occasionally exploits sexually, he forms a close relationship with a seaside landlady with whom he eventually lives incognito in Chelsea, where he dies. Throughout this, he travels, paints, stays with the country aristocracy, visits brothels, is a popular if anarchic member of the Royal Academy of Arts, has himself strapped to the mast of a ship so that he can paint a snowstorm, and is both celebrated and reviled by the public and by royalty."),
            new Movie(R.drawable.paddington, "PADDINGTON", "Dec 3, 2014 Wide", "From the beloved novels by Michael Bond and producer David Heyman (HARRY POTTER), PADDINGTON tells the story of the comic misadventures of a young Peruvian bear (voiced by Firth) who travels to the city in search of a home. Finding himself lost and alone, he begins to realize that city life is not all he had imagined - until he meets the kindly Brown family who read the label around his neck that says \"Please look after this bear. Thank you,\" and offer him a temporary haven. It looks as though his luck has changed until this rarest of bears catches the eye of a museum taxidermist. (c) Weinstein"),
            new Movie(R.drawable.la_nuit_du_chasseur, "LA NUIT DU CHASSEUR", "1955", "Adapted by James Agee from a novel by Davis Grubb, The Night of the Hunter represented legendary actor Charles Laughton's only film directing effort. Combining stark realism with Germanic expressionism, the movie is a brilliant good-and-evil parable, with \"good\" represented by a couple of farm kids and a pious old lady, and \"evil\" literally in the hands of a posturing psychopath. Imprisoned with thief Ben Harper (Peter Graves), phony preacher Harry Powell (Robert Mitchum) learns that Ben has hidden a huge sum of money somewhere near his home. Upon his release, the murderously misogynistic Powell insinuates himself into Ben's home, eventually marrying his widow Willa (Shelley Winters). Eventually all that stands between Powell and the money are Ben's son (Billy Chapin) and daughter (Sally Jane Bruce), who take refuge in a home for abandoned children presided over by the indomitable, scripture-quoting Rachel Cooper (Lillian Gish). The war of wills between Mitchum and Gish is the heart of the film's final third, a masterful blend of horror and lyricism. Laughton's tight, disciplined direction is superb -- and all the more impressive when one realizes that he intensely disliked all child actors. The music by Walter Schumann and the cinematography of Stanley Cortez are every bit as brilliant as the contributions by Laughton and Agee. Overlooked on its first release, The Night of the Hunter is now regarded as a classic. ~ Hal Erickson, Rovi")
    );
}
